const DEFAULT_MAX_APPLICATIONS_PER_USER = '99';
const DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES = '15';
const DEFAULT_OAUTH2_ACCESS_TOKEN_FALLBACK_TTL_SECONDS = '3600';
const DEFAULT_MAX_CALDAV_CREDENTIALS_PER_APPLICATION = '5';
const DEFAULT_DEFAULT_CALDAV_CREDENTIAL_EXPIRY_DAYS = '365';
const DEFAULT_MAX_CALDAV_CREDENTIAL_EXPIRY_DAYS = '365';

export {
  DEFAULT_DEFAULT_CALDAV_CREDENTIAL_EXPIRY_DAYS,
  DEFAULT_MAX_APPLICATIONS_PER_USER,
  DEFAULT_MAX_CALDAV_CREDENTIALS_PER_APPLICATION,
  DEFAULT_MAX_CALDAV_CREDENTIAL_EXPIRY_DAYS,
  DEFAULT_OAUTH2_ACCESS_TOKEN_FALLBACK_TTL_SECONDS,
  DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES,
};
