const PROVIDER_GOOGLE_CALENDAR = 'google-calendar';
const PROVIDER_MICROSOFT_OUTLOOK_CALENDAR = 'microsoft-outlook-calendar';

const CONNECTION_METHOD_OAUTH2 = 'oauth2';

const CONNECTED_APPLICATION_STATUS_DRAFT = 'draft';
const CONNECTED_APPLICATION_STATUS_CONNECTED = 'connected';
const CONNECTED_APPLICATION_STATUS_ERROR = 'error';

const SUPPORTED_PROVIDER_CONNECTIONS = {
  [PROVIDER_GOOGLE_CALENDAR]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_MICROSOFT_OUTLOOK_CALENDAR]: CONNECTION_METHOD_OAUTH2,
} as const;

type ProviderId = keyof typeof SUPPORTED_PROVIDER_CONNECTIONS;
type ConnectionMethod = (typeof SUPPORTED_PROVIDER_CONNECTIONS)[ProviderId];
type ConnectedApplicationStatus =
  | typeof CONNECTED_APPLICATION_STATUS_DRAFT
  | typeof CONNECTED_APPLICATION_STATUS_CONNECTED
  | typeof CONNECTED_APPLICATION_STATUS_ERROR;

export {
  CONNECTED_APPLICATION_STATUS_CONNECTED,
  CONNECTED_APPLICATION_STATUS_DRAFT,
  CONNECTED_APPLICATION_STATUS_ERROR,
  CONNECTION_METHOD_OAUTH2,
  PROVIDER_GOOGLE_CALENDAR,
  PROVIDER_MICROSOFT_OUTLOOK_CALENDAR,
  SUPPORTED_PROVIDER_CONNECTIONS,
};
export type { ConnectedApplicationStatus, ConnectionMethod, ProviderId };
